import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { ArrowLeft, Pencil, Trash2, Mail, Phone, MapPin, Target, CalendarDays, MessageSquare, FlaskConical, CheckSquare, StickyNote, UserCheck } from "lucide-react";
import { useStore, useHydrated, fmtDate, fmtDateTime, fmtMoney } from "@/lib/store";
import { PageHeader, LoadingBlock, StatusBadge, ConfirmDialog, Section, DefinitionList, EmptyState } from "@/components/shared";
import { ProspectDialog } from "@/components/prospects/ProspectDialog";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";

export const Route = createFileRoute("/_app/prospects/$id")({
  head: () => ({ meta: [{ title: "Fiche prospect — Atelier du Zellige" }, { name: "description", content: "Fiche prospect détaillée : coordonnées, projet, notes, tâches, rendez-vous, échantillons et échanges." }, { property: "og:title", content: "Fiche prospect — Atelier du Zellige" }, { property: "og:description", content: "Détails et historique d'un prospect du CRM." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }),
  component: ProspectDetail,
});

function ProspectDetail() {
  const { id } = Route.useParams(); const hydrated = useHydrated(); const navigate = useNavigate(); const s = useStore();
  const prospect = s.prospects.find((p) => p.id === id); const [edit, setEdit] = useState(false); const [del, setDel] = useState(false); const [note, setNote] = useState("");
  if (!hydrated) return <LoadingBlock />;
  if (!prospect) return <EmptyState icon={Target} title="Prospect introuvable" description="Ce prospect n'existe pas ou a été supprimé." action={<Button asChild variant="outline"><Link to="/prospects"><ArrowLeft className="h-4 w-4" /> Retour aux prospects</Link></Button>} />;
  const tasks = s.tasks.filter((t) => t.relatedType === "prospect" && t.relatedId === id); const appointments = s.appointments.filter((a) => a.contactType === "prospect" && a.contactId === id); const samples = s.samples.filter((x) => x.contactType === "prospect" && x.contactId === id); const messages = s.messages.filter((m) => m.contactType === "prospect" && m.contactId === id); const activities = s.activities.filter((a) => a.target.includes(prospect.name) || a.link === `/prospects/${id}`);
  const addNote = () => { if (!note.trim()) return; s.addProspectNote(id, note.trim()); s.log({ agent: "Utilisateur", action: "Note prospect", target: prospect.name, result: note.trim().slice(0, 60), status: "Succès", link: `/prospects/${id}` }); setNote(""); toast.success("Note ajoutée."); };
  const convert = () => { const client = s.convertProspect(id); if (client) navigate({ to: "/clients/$id", params: { id: client.id } }); };
  return <div>
    <Button variant="ghost" size="sm" className="mb-3 -ml-2" asChild><Link to="/prospects"><ArrowLeft className="h-4 w-4" /> Prospects</Link></Button>
    <PageHeader eyebrow="CRM" title={prospect.name} description={`${prospect.company} · ${prospect.project}`} actions={<><StatusBadge status={prospect.stage} className="h-8 px-3 text-sm" /><Button variant="outline" onClick={() => setEdit(true)}><Pencil className="h-4 w-4" /> Modifier</Button><Button variant="outline" className="text-destructive" onClick={() => setDel(true)}><Trash2 className="h-4 w-4" /> Supprimer</Button>{prospect.convertedClientId ? <Button asChild className="bg-gold text-gold-foreground hover:bg-gold/90"><Link to="/clients/$id" params={{ id: prospect.convertedClientId }}><UserCheck className="h-4 w-4" /> Voir le client</Link></Button> : <Button className="bg-gold text-gold-foreground hover:bg-gold/90" onClick={convert}><UserCheck className="h-4 w-4" /> Convertir en client</Button>}</>} />
    <div className="grid gap-4 xl:grid-cols-3"><div className="space-y-4">
      <Section title="Informations générales"><div className="mb-4 flex items-center gap-3"><Avatar className="h-12 w-12"><AvatarFallback className="bg-charcoal text-charcoal-foreground">{prospect.name.split(" ").map((x) => x[0]).slice(0, 2).join("")}</AvatarFallback></Avatar><div><div className="font-medium">{prospect.name}</div><div className="text-sm text-muted-foreground">{prospect.company}</div></div></div><DefinitionList items={[{ label: "Source", value: prospect.source }, { label: "Créé le", value: fmtDate(prospect.createdAt) }, { label: "Dernière activité", value: fmtDate(prospect.lastActivity) }, { label: "Valeur estimée", value: fmtMoney(prospect.estimatedValue) }, { label: "Score", value: `${prospect.score}/100` }, { label: "Étape", value: <StatusBadge status={prospect.stage} /> }]} /></Section>
      <Section title="Coordonnées"><ul className="space-y-2.5 text-sm"><li className="flex items-center gap-2"><Mail className="h-4 w-4 text-muted-foreground" /><a href={`mailto:${prospect.email}`} className="hover:underline">{prospect.email}</a></li><li className="flex items-center gap-2"><Phone className="h-4 w-4 text-muted-foreground" />{prospect.phone || "—"}</li><li className="flex items-center gap-2"><MapPin className="h-4 w-4 text-muted-foreground" />{prospect.country || "—"}</li></ul></Section>
      <Section title="Projet"><p className="text-sm leading-relaxed">{prospect.project}</p></Section>
      <Section title="Notes"><div className="space-y-3">{prospect.notes.length ? prospect.notes.map((n) => <div key={n.id} className="rounded-md border bg-secondary/30 p-3"><p className="text-sm">{n.text}</p><p className="mt-1 text-[11px] text-muted-foreground">{fmtDateTime(n.date)}</p></div>) : <p className="text-sm text-muted-foreground">Aucune note.</p>}</div><div className="mt-3 flex gap-2"><Textarea rows={2} placeholder="Ajouter une note…" value={note} onChange={(e) => setNote(e.target.value)} /><Button size="sm" variant="outline" onClick={addNote} disabled={!note.trim()}>Ajouter</Button></div></Section>
    </div><div className="xl:col-span-2"><Tabs defaultValue="tasks"><TabsList className="mb-3 flex-wrap"><TabsTrigger value="tasks"><CheckSquare className="h-3.5 w-3.5" /> Tâches ({tasks.length})</TabsTrigger><TabsTrigger value="appointments"><CalendarDays className="h-3.5 w-3.5" /> Rendez-vous ({appointments.length})</TabsTrigger><TabsTrigger value="samples"><FlaskConical className="h-3.5 w-3.5" /> Échantillons ({samples.length})</TabsTrigger><TabsTrigger value="messages"><MessageSquare className="h-3.5 w-3.5" /> Échanges ({messages.length})</TabsTrigger><TabsTrigger value="activity"><StickyNote className="h-3.5 w-3.5" /> Activité</TabsTrigger></TabsList>
      <TabsContent value="tasks"><List items={tasks.map((t) => <button key={t.id} type="button" onClick={() => s.toggleTask(t.id)} className="flex w-full items-center gap-3 px-5 py-3 text-left"><span className={`h-4 w-4 rounded border ${t.done ? "border-success bg-success" : "bg-card"}`} /><span className={`flex-1 text-sm ${t.done ? "line-through text-muted-foreground" : ""}`}>{t.title}</span><span className="text-xs text-muted-foreground">{fmtDate(t.dueDate)}</span></button>)} empty="Aucune tâche" /></TabsContent>
      <TabsContent value="appointments"><List items={appointments.map((a) => <div key={a.id} className="flex items-center gap-4 px-5 py-3"><span className="font-medium">{a.title}</span><span className="flex-1 text-sm text-muted-foreground">{a.type}</span><span className="text-sm text-muted-foreground">{fmtDateTime(a.start)}</span><StatusBadge status={a.status} /></div>)} empty="Aucun rendez-vous" /></TabsContent>
      <TabsContent value="samples"><List items={samples.map((x) => <div key={x.id} className="flex items-center gap-4 px-5 py-3"><span className="font-medium">{x.reference}</span><span className="flex-1 truncate text-sm text-muted-foreground">{s.products.find((p) => p.id === x.productId)?.name} × {x.quantity}</span><StatusBadge status={x.status} /></div>)} empty="Aucun échantillon" /></TabsContent>
      <TabsContent value="messages"><List items={messages.map((m) => <div key={m.id} className="px-5 py-3"><div className="flex gap-2 text-sm"><span className={m.direction === "in" ? "text-info" : "text-gold"}>{m.direction === "in" ? "Reçu" : "Envoyé"}</span><span className="font-medium">{m.subject}</span><span className="ml-auto text-xs text-muted-foreground">{fmtDateTime(m.date)}</span></div><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{m.body}</p></div>)} empty="Aucun échange" /></TabsContent>
      <TabsContent value="activity"><List items={activities.slice(0, 15).map((a) => <div key={a.id} className="flex items-center gap-4 px-5 py-3 text-sm"><span className="w-28 text-xs text-muted-foreground">{fmtDateTime(a.date)}</span><span className="font-medium">{a.agent}</span><span className="flex-1 truncate text-muted-foreground">{a.action} — {a.result}</span><StatusBadge status={a.status} /></div>)} empty="Aucune activité" /></TabsContent>
    </Tabs></div></div>
    <ProspectDialog open={edit} onOpenChange={setEdit} prospect={prospect} /><ConfirmDialog open={del} onOpenChange={setDel} title={`Supprimer ${prospect.name} ?`} onConfirm={() => { s.deleteProspect(id); toast.success("Élément supprimé."); navigate({ to: "/prospects" }); }} />
  </div>;
}
function List({ items, empty }: { items: React.ReactNode[]; empty: string }) { return <Section noPadding>{items.length ? <div className="divide-y">{items}</div> : <div className="p-8 text-center text-sm text-muted-foreground">{empty}</div>}</Section>; }
