/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppCommunicationRouteImport } from './routes/_app/communication'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppEchantillonsRouteImport } from './routes/_app/echantillons'
import { Route as AppExportRouteImport } from './routes/_app/export'
import { Route as AppParametresRouteImport } from './routes/_app/parametres'
import { Route as AppProductionRouteImport } from './routes/_app/production'
import { Route as AppProduitsRouteImport } from './routes/_app/produits'
import { Route as AppProspectsRouteImport } from './routes/_app/prospects'
import { Route as AppRendezVousRouteImport } from './routes/_app/rendez-vous'
import { Route as AppAgentsIndexRouteImport } from './routes/_app/agents/index'
import { Route as AppAgentsActiviteRouteImport } from './routes/_app/agents/activite'
import { Route as AppAgentsBookingRouteImport } from './routes/_app/agents/booking'
import { Route as AppAgentsRelancesRouteImport } from './routes/_app/agents/relances'
import { Route as AppAgentsServiceClientRouteImport } from './routes/_app/agents/service-client'
import { Route as AppAgentsSuiviCommandesRouteImport } from './routes/_app/agents/suivi-commandes'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients/index'
import { Route as AppClientsIdRouteImport } from './routes/_app/clients/$id'
import { Route as AppCommandesIndexRouteImport } from './routes/_app/commandes/index'
import { Route as AppCommandesIdRouteImport } from './routes/_app/commandes/$id'
import { Route as AppDevisIndexRouteImport } from './routes/_app/devis/index'
import { Route as AppDevisIdRouteImport } from './routes/_app/devis/$id'
import { Route as AppProspectsIdRouteImport } from './routes/_app/prospects/$id'
import { Route as AppAgentsCmIndexRouteImport } from './routes/_app/agents/cm/index'
import { Route as AppAgentsCmIdeesRouteImport } from './routes/_app/agents/cm/idees'
import { Route as AppAgentsCmParametresRouteImport } from './routes/_app/agents/cm/parametres'
import { Route as AppAgentsCmPlanningRouteImport } from './routes/_app/agents/cm/planning'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommunicationRoute = AppCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEchantillonsRoute = AppEchantillonsRouteImport.update({
  id: '/echantillons',
  path: '/echantillons',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProduitsRoute = AppProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProspectsRoute = AppProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRendezVousRoute = AppRendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentsActiviteRoute = AppAgentsActiviteRouteImport.update({
  id: '/agents/activite',
  path: '/agents/activite',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentsBookingRoute = AppAgentsBookingRouteImport.update({
  id: '/agents/booking',
  path: '/agents/booking',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentsRelancesRoute = AppAgentsRelancesRouteImport.update({
  id: '/agents/relances',
  path: '/agents/relances',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentsServiceClientRoute = AppAgentsServiceClientRouteImport.update({
  id: '/agents/service-client',
  path: '/agents/service-client',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentsSuiviCommandesRoute = AppAgentsSuiviCommandesRouteImport.update({
  id: '/agents/suivi-commandes',
  path: '/agents/suivi-commandes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommandesIndexRoute = AppCommandesIndexRouteImport.update({
  id: '/commandes/',
  path: '/commandes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommandesIdRoute = AppCommandesIdRouteImport.update({
  id: '/commandes/$id',
  path: '/commandes/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDevisIndexRoute = AppDevisIndexRouteImport.update({
  id: '/devis/',
  path: '/devis/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDevisIdRoute = AppDevisIdRouteImport.update({
  id: '/devis/$id',
  path: '/devis/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProspectsIdRoute = AppProspectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProspectsRoute,
} as any)
const AppAgentsCmIndexRoute = AppAgentsCmIndexRouteImport.update({
  id: '/agents/cm/',
  path: '/agents/cm/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentsCmIdeesRoute = AppAgentsCmIdeesRouteImport.update({
  id: '/agents/cm/idees',
  path: '/agents/cm/idees',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentsCmParametresRoute = AppAgentsCmParametresRouteImport.update({
  id: '/agents/cm/parametres',
  path: '/agents/cm/parametres',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentsCmPlanningRoute = AppAgentsCmPlanningRouteImport.update({
  id: '/agents/cm/planning',
  path: '/agents/cm/planning',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/communication': typeof AppCommunicationRoute
  '/dashboard': typeof AppDashboardRoute
  '/echantillons': typeof AppEchantillonsRoute
  '/export': typeof AppExportRoute
  '/parametres': typeof AppParametresRoute
  '/production': typeof AppProductionRoute
  '/produits': typeof AppProduitsRoute
  '/prospects': typeof AppProspectsRouteWithChildren
  '/rendez-vous': typeof AppRendezVousRoute
  '/agents/activite': typeof AppAgentsActiviteRoute
  '/agents/booking': typeof AppAgentsBookingRoute
  '/agents/relances': typeof AppAgentsRelancesRoute
  '/agents/service-client': typeof AppAgentsServiceClientRoute
  '/agents/suivi-commandes': typeof AppAgentsSuiviCommandesRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/commandes/$id': typeof AppCommandesIdRoute
  '/devis/$id': typeof AppDevisIdRoute
  '/prospects/$id': typeof AppProspectsIdRoute
  '/agents/': typeof AppAgentsIndexRoute
  '/clients/': typeof AppClientsIndexRoute
  '/commandes/': typeof AppCommandesIndexRoute
  '/devis/': typeof AppDevisIndexRoute
  '/agents/cm/idees': typeof AppAgentsCmIdeesRoute
  '/agents/cm/parametres': typeof AppAgentsCmParametresRoute
  '/agents/cm/planning': typeof AppAgentsCmPlanningRoute
  '/agents/cm/': typeof AppAgentsCmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/communication': typeof AppCommunicationRoute
  '/dashboard': typeof AppDashboardRoute
  '/echantillons': typeof AppEchantillonsRoute
  '/export': typeof AppExportRoute
  '/parametres': typeof AppParametresRoute
  '/production': typeof AppProductionRoute
  '/produits': typeof AppProduitsRoute
  '/prospects': typeof AppProspectsRouteWithChildren
  '/rendez-vous': typeof AppRendezVousRoute
  '/agents/activite': typeof AppAgentsActiviteRoute
  '/agents/booking': typeof AppAgentsBookingRoute
  '/agents/relances': typeof AppAgentsRelancesRoute
  '/agents/service-client': typeof AppAgentsServiceClientRoute
  '/agents/suivi-commandes': typeof AppAgentsSuiviCommandesRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/commandes/$id': typeof AppCommandesIdRoute
  '/devis/$id': typeof AppDevisIdRoute
  '/prospects/$id': typeof AppProspectsIdRoute
  '/agents': typeof AppAgentsIndexRoute
  '/clients': typeof AppClientsIndexRoute
  '/commandes': typeof AppCommandesIndexRoute
  '/devis': typeof AppDevisIndexRoute
  '/agents/cm/idees': typeof AppAgentsCmIdeesRoute
  '/agents/cm/parametres': typeof AppAgentsCmParametresRoute
  '/agents/cm/planning': typeof AppAgentsCmPlanningRoute
  '/agents/cm': typeof AppAgentsCmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/communication': typeof AppCommunicationRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/echantillons': typeof AppEchantillonsRoute
  '/_app/export': typeof AppExportRoute
  '/_app/parametres': typeof AppParametresRoute
  '/_app/production': typeof AppProductionRoute
  '/_app/produits': typeof AppProduitsRoute
  '/_app/prospects': typeof AppProspectsRouteWithChildren
  '/_app/rendez-vous': typeof AppRendezVousRoute
  '/_app/agents/activite': typeof AppAgentsActiviteRoute
  '/_app/agents/booking': typeof AppAgentsBookingRoute
  '/_app/agents/relances': typeof AppAgentsRelancesRoute
  '/_app/agents/service-client': typeof AppAgentsServiceClientRoute
  '/_app/agents/suivi-commandes': typeof AppAgentsSuiviCommandesRoute
  '/_app/clients/$id': typeof AppClientsIdRoute
  '/_app/commandes/$id': typeof AppCommandesIdRoute
  '/_app/devis/$id': typeof AppDevisIdRoute
  '/_app/prospects/$id': typeof AppProspectsIdRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/commandes/': typeof AppCommandesIndexRoute
  '/_app/devis/': typeof AppDevisIndexRoute
  '/_app/agents/cm/idees': typeof AppAgentsCmIdeesRoute
  '/_app/agents/cm/parametres': typeof AppAgentsCmParametresRoute
  '/_app/agents/cm/planning': typeof AppAgentsCmPlanningRoute
  '/_app/agents/cm/': typeof AppAgentsCmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/communication'
    | '/dashboard'
    | '/echantillons'
    | '/export'
    | '/parametres'
    | '/production'
    | '/produits'
    | '/prospects'
    | '/rendez-vous'
    | '/agents/activite'
    | '/agents/booking'
    | '/agents/relances'
    | '/agents/service-client'
    | '/agents/suivi-commandes'
    | '/clients/$id'
    | '/commandes/$id'
    | '/devis/$id'
    | '/prospects/$id'
    | '/agents/'
    | '/clients/'
    | '/commandes/'
    | '/devis/'
    | '/agents/cm/idees'
    | '/agents/cm/parametres'
    | '/agents/cm/planning'
    | '/agents/cm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/communication'
    | '/dashboard'
    | '/echantillons'
    | '/export'
    | '/parametres'
    | '/production'
    | '/produits'
    | '/prospects'
    | '/rendez-vous'
    | '/agents/activite'
    | '/agents/booking'
    | '/agents/relances'
    | '/agents/service-client'
    | '/agents/suivi-commandes'
    | '/clients/$id'
    | '/commandes/$id'
    | '/devis/$id'
    | '/prospects/$id'
    | '/agents'
    | '/clients'
    | '/commandes'
    | '/devis'
    | '/agents/cm/idees'
    | '/agents/cm/parametres'
    | '/agents/cm/planning'
    | '/agents/cm'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/analytics'
    | '/_app/communication'
    | '/_app/dashboard'
    | '/_app/echantillons'
    | '/_app/export'
    | '/_app/parametres'
    | '/_app/production'
    | '/_app/produits'
    | '/_app/prospects'
    | '/_app/rendez-vous'
    | '/_app/agents/activite'
    | '/_app/agents/booking'
    | '/_app/agents/relances'
    | '/_app/agents/service-client'
    | '/_app/agents/suivi-commandes'
    | '/_app/clients/$id'
    | '/_app/commandes/$id'
    | '/_app/devis/$id'
    | '/_app/prospects/$id'
    | '/_app/agents/'
    | '/_app/clients/'
    | '/_app/commandes/'
    | '/_app/devis/'
    | '/_app/agents/cm/idees'
    | '/_app/agents/cm/parametres'
    | '/_app/agents/cm/planning'
    | '/_app/agents/cm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/communication': {
      id: '/_app/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof AppCommunicationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/echantillons': {
      id: '/_app/echantillons'
      path: '/echantillons'
      fullPath: '/echantillons'
      preLoaderRoute: typeof AppEchantillonsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/export': {
      id: '/_app/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/parametres': {
      id: '/_app/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/production': {
      id: '/_app/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/produits': {
      id: '/_app/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof AppProduitsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/prospects': {
      id: '/_app/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof AppProspectsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rendez-vous': {
      id: '/_app/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/rendez-vous'
      preLoaderRoute: typeof AppRendezVousRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agents/activite': {
      id: '/_app/agents/activite'
      path: '/agents/activite'
      fullPath: '/agents/activite'
      preLoaderRoute: typeof AppAgentsActiviteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agents/booking': {
      id: '/_app/agents/booking'
      path: '/agents/booking'
      fullPath: '/agents/booking'
      preLoaderRoute: typeof AppAgentsBookingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agents/relances': {
      id: '/_app/agents/relances'
      path: '/agents/relances'
      fullPath: '/agents/relances'
      preLoaderRoute: typeof AppAgentsRelancesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agents/service-client': {
      id: '/_app/agents/service-client'
      path: '/agents/service-client'
      fullPath: '/agents/service-client'
      preLoaderRoute: typeof AppAgentsServiceClientRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agents/suivi-commandes': {
      id: '/_app/agents/suivi-commandes'
      path: '/agents/suivi-commandes'
      fullPath: '/agents/suivi-commandes'
      preLoaderRoute: typeof AppAgentsSuiviCommandesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/clients/$id': {
      id: '/_app/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/commandes/': {
      id: '/_app/commandes/'
      path: '/commandes'
      fullPath: '/commandes/'
      preLoaderRoute: typeof AppCommandesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/commandes/$id': {
      id: '/_app/commandes/$id'
      path: '/commandes/$id'
      fullPath: '/commandes/$id'
      preLoaderRoute: typeof AppCommandesIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/devis/': {
      id: '/_app/devis/'
      path: '/devis'
      fullPath: '/devis/'
      preLoaderRoute: typeof AppDevisIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/devis/$id': {
      id: '/_app/devis/$id'
      path: '/devis/$id'
      fullPath: '/devis/$id'
      preLoaderRoute: typeof AppDevisIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/prospects/$id': {
      id: '/_app/prospects/$id'
      path: '/$id'
      fullPath: '/prospects/$id'
      preLoaderRoute: typeof AppProspectsIdRouteImport
      parentRoute: typeof AppProspectsRoute
    }
    '/_app/agents/cm/': {
      id: '/_app/agents/cm/'
      path: '/agents/cm'
      fullPath: '/agents/cm/'
      preLoaderRoute: typeof AppAgentsCmIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agents/cm/idees': {
      id: '/_app/agents/cm/idees'
      path: '/agents/cm/idees'
      fullPath: '/agents/cm/idees'
      preLoaderRoute: typeof AppAgentsCmIdeesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agents/cm/parametres': {
      id: '/_app/agents/cm/parametres'
      path: '/agents/cm/parametres'
      fullPath: '/agents/cm/parametres'
      preLoaderRoute: typeof AppAgentsCmParametresRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agents/cm/planning': {
      id: '/_app/agents/cm/planning'
      path: '/agents/cm/planning'
      fullPath: '/agents/cm/planning'
      preLoaderRoute: typeof AppAgentsCmPlanningRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppProspectsRouteChildren {
  AppProspectsIdRoute: typeof AppProspectsIdRoute
}

const AppProspectsRouteChildren: AppProspectsRouteChildren = {
  AppProspectsIdRoute: AppProspectsIdRoute,
}

const AppProspectsRouteWithChildren = AppProspectsRoute._addFileChildren(
  AppProspectsRouteChildren,
)

interface AppRouteRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCommunicationRoute: typeof AppCommunicationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEchantillonsRoute: typeof AppEchantillonsRoute
  AppExportRoute: typeof AppExportRoute
  AppParametresRoute: typeof AppParametresRoute
  AppProductionRoute: typeof AppProductionRoute
  AppProduitsRoute: typeof AppProduitsRoute
  AppProspectsRoute: typeof AppProspectsRouteWithChildren
  AppRendezVousRoute: typeof AppRendezVousRoute
  AppAgentsActiviteRoute: typeof AppAgentsActiviteRoute
  AppAgentsBookingRoute: typeof AppAgentsBookingRoute
  AppAgentsRelancesRoute: typeof AppAgentsRelancesRoute
  AppAgentsServiceClientRoute: typeof AppAgentsServiceClientRoute
  AppAgentsSuiviCommandesRoute: typeof AppAgentsSuiviCommandesRoute
  AppClientsIdRoute: typeof AppClientsIdRoute
  AppCommandesIdRoute: typeof AppCommandesIdRoute
  AppDevisIdRoute: typeof AppDevisIdRoute
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppCommandesIndexRoute: typeof AppCommandesIndexRoute
  AppDevisIndexRoute: typeof AppDevisIndexRoute
  AppAgentsCmIdeesRoute: typeof AppAgentsCmIdeesRoute
  AppAgentsCmParametresRoute: typeof AppAgentsCmParametresRoute
  AppAgentsCmPlanningRoute: typeof AppAgentsCmPlanningRoute
  AppAgentsCmIndexRoute: typeof AppAgentsCmIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCommunicationRoute: AppCommunicationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEchantillonsRoute: AppEchantillonsRoute,
  AppExportRoute: AppExportRoute,
  AppParametresRoute: AppParametresRoute,
  AppProductionRoute: AppProductionRoute,
  AppProduitsRoute: AppProduitsRoute,
  AppProspectsRoute: AppProspectsRouteWithChildren,
  AppRendezVousRoute: AppRendezVousRoute,
  AppAgentsActiviteRoute: AppAgentsActiviteRoute,
  AppAgentsBookingRoute: AppAgentsBookingRoute,
  AppAgentsRelancesRoute: AppAgentsRelancesRoute,
  AppAgentsServiceClientRoute: AppAgentsServiceClientRoute,
  AppAgentsSuiviCommandesRoute: AppAgentsSuiviCommandesRoute,
  AppClientsIdRoute: AppClientsIdRoute,
  AppCommandesIdRoute: AppCommandesIdRoute,
  AppDevisIdRoute: AppDevisIdRoute,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppCommandesIndexRoute: AppCommandesIndexRoute,
  AppDevisIndexRoute: AppDevisIndexRoute,
  AppAgentsCmIdeesRoute: AppAgentsCmIdeesRoute,
  AppAgentsCmParametresRoute: AppAgentsCmParametresRoute,
  AppAgentsCmPlanningRoute: AppAgentsCmPlanningRoute,
  AppAgentsCmIndexRoute: AppAgentsCmIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
